---
title: "3D Gene Regulation in Humans and Chimpanzees"
output:
  html_document:
    toc: false
---

This website details computational analyses done on my thesis project, which utilizes Hi-C to find 3-dimensional regulatory differences between humans and chimpanzees. Click on any of the links below to jump to that section of the analysis. Note that I repeated the same types of analyses using different normalization and significance-calling schmes; these are the larger headers:

#### Analyses Utilizing Homer
*  [Reading in of the data, normalization, and initial quality control metrics](initial_QC.html)
*  [Linear modeling of the data to find quantitative contact differences between humans and chimpanzees](linear_modeling.html)
*  [Quality control on the linear modeling, to account for p-value inflation and volcano plot asymmetry](linear_modeling_QC.html)
*  [Enrichment analyses on the linear-modeling significant Hi-C hits](enrichment.html)
*  [Orthogonal analysis with gene expression data collected from the same cell lines](gene_expression.html)

#### Analyses Utilizing Juicer
*  [Reading in of the data, normalization, and initial quality control metrics](juicer_initial_QC.html)
*  [Linear modeling of the data to find quantitative contact differences between humans and chimpanzees](juicer_linear_modeling.html)
*  [Quality control on the linear modeling, to account for p-value inflation and volcano plot asymmetry](juicer_linear_modeling_QC.html)
*  [Orthogonal analysis with gene expression data collected from the same cell lines](juicer_gene_expression.html)
*  [Enrichment analyses on the linear-modeling significant Hi-C hits](juicer_enrichment.html)